In [12]:
import torch
from torch import nn

In [15]:
torch.mps.device_count()

1

In [38]:
def try_gpu(i=0):
    if torch.cuda.is_available():
        return torch.device(f'cuda:{i}')
    elif torch.backends.mps.is_available():
        return torch.device('mps')
    else:
        return torch.device('cpu')
    
try_gpu(0)

device(type='mps')

In [22]:
x = torch.tensor([1, 2, 3])
x.device

device(type='cpu')

### 存储在GPU上

In [23]:
x = torch.ones(2, 3, device=try_gpu())
x

tensor([[1., 1., 1.],
        [1., 1., 1.]], device='mps:0')

### 第二个GPU上创建一个随机张量

In [25]:
Y = torch.rand(2, 3, device=try_gpu())
Y

tensor([[0.5732, 0.3326, 0.0860],
        [0.1996, 0.3917, 0.4958]], device='mps:0')

In [33]:
x + Y

tensor([[1.5732, 1.3326, 1.0860],
        [1.1996, 1.3917, 1.4958]], device='mps:0')

### 神经网络

In [41]:
net = nn.Sequential(nn.Linear(3, 1))
net = net.to(device = try_gpu())

net(x)

tensor([[-0.9582],
        [-0.9582]], device='mps:0', grad_fn=<LinearBackward0>)

In [43]:
net[0].weight.data

tensor([[ 0.3201, -0.4883, -0.2630]], device='mps:0')