In [1]:
import torch
from torch import nn

print(torch.backends.mps.is_available())

True


In [2]:
def try_gpu(i=0):
    if torch.cuda.is_available():
        return torch.device(f'cuda:{i}')
    elif torch.backends.mps.is_available():
        return torch.device('mps')
    else:
        return torch.device('cpu')
    
try_gpu(0)

device(type='mps')

In [3]:
x = torch.tensor([1, 2, 3])
x.device

device(type='cpu')

### 存储在GPU上

In [4]:
x = torch.ones(2, 3, device=try_gpu())
x

tensor([[1., 1., 1.],
        [1., 1., 1.]], device='mps:0')

### 第二个GPU上创建一个随机张量

In [5]:
Y = torch.rand(2, 3, device=try_gpu())
Y

tensor([[0.6976, 0.5699, 0.5293],
        [0.8588, 0.3617, 0.3066]], device='mps:0')

In [6]:
x + Y

tensor([[1.6976, 1.5699, 1.5293],
        [1.8588, 1.3617, 1.3066]], device='mps:0')

### 神经网络

In [7]:
net = nn.Sequential(nn.Linear(3, 1))
net = net.to(device = try_gpu())

net(x)

tensor([[-0.2379],
        [-0.2379]], device='mps:0', grad_fn=<LinearBackward0>)

In [8]:
net[0].weight.data

tensor([[-0.0669, -0.4280,  0.5467]], device='mps:0')