In [3]:
import torch
from torch import nn

print(torch.backends.mps.is_available())

True


In [4]:
def try_gpu(i=0):
    if torch.cuda.is_available():
        return torch.device(f'cuda:{i}')
    elif torch.backends.mps.is_available():
        return torch.device('mps')
    else:
        return torch.device('cpu')
    
try_gpu(0)

device(type='mps')

In [5]:
x = torch.tensor([1, 2, 3])
x.device

device(type='cpu')

### 存储在GPU上

In [6]:
x = torch.ones(2, 3, device=try_gpu())
x

/opt/homebrew/Caskroom/miniforge/base/envs/d2l/lib/python3.9/site-packages/torch/_tensor_str.py:115: UserWarning: The operator 'aten::nonzero' is not currently supported on the MPS backend and will fall back to run on the CPU. This may have performance implications. (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/mps/MPSFallback.mm:11.)
  nonzero_finite_vals = torch.masked_select(


tensor([[1., 1., 1.],
        [1., 1., 1.]], device='mps:0')

### 第二个GPU上创建一个随机张量

In [7]:
Y = torch.rand(2, 3, device=try_gpu())
Y

tensor([[0.9328, 0.5569, 0.0771],
        [0.0297, 0.7839, 0.5505]], device='mps:0')

In [8]:
x + Y

tensor([[1.9328, 1.5569, 1.0771],
        [1.0297, 1.7839, 1.5505]], device='mps:0')

### 神经网络

In [9]:
net = nn.Sequential(nn.Linear(3, 1))
net = net.to(device = try_gpu())

net(x)

tensor([[-1.1400],
        [-1.1400]], device='mps:0', grad_fn=<LinearBackward0>)

In [10]:
net[0].weight.data

tensor([[-0.5405, -0.2923,  0.0259]], device='mps:0')