In [1]:
import torch
from torch import nn

print(torch.backends.mps.is_available())

False


In [2]:
def try_gpu(i=0):
    if torch.cuda.is_available():
        return torch.device(f'cuda:{i}')
    elif torch.backends.mps.is_available():
        return torch.device('mps')
    else:
        return torch.device('cpu')
    
try_gpu(0)

device(type='cuda', index=0)

In [3]:
x = torch.tensor([1, 2, 3])
x.device

device(type='cpu')

### 存储在GPU上

In [4]:
x = torch.ones(2, 3, device=try_gpu())
x

tensor([[1., 1., 1.],
        [1., 1., 1.]], device='cuda:0')

### 第二个GPU上创建一个随机张量

In [5]:
Y = torch.rand(2, 3, device=try_gpu())
Y

tensor([[0.4808, 0.1096, 0.7796],
        [0.1968, 0.5104, 0.9128]], device='cuda:0')

In [6]:
x + Y

tensor([[1.4808, 1.1096, 1.7796],
        [1.1968, 1.5104, 1.9128]], device='cuda:0')

### 神经网络

In [7]:
net = nn.Sequential(nn.Linear(3, 1))
net = net.to(device = try_gpu())

net(x)

tensor([[0.0115],
        [0.0115]], device='cuda:0', grad_fn=<AddmmBackward0>)

In [8]:
net[0].weight.data

tensor([[-0.1225, -0.1268,  0.4800]], device='cuda:0')