In [2]:
import torch

#### 向量

In [4]:
x = torch.arange(4)

#### 矩阵

In [16]:
A = torch.arange(16).reshape(4, 4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])

In [17]:
A.T

tensor([[ 0,  4,  8, 12],
        [ 1,  5,  9, 13],
        [ 2,  6, 10, 14],
        [ 3,  7, 11, 15]])

In [20]:
A == A.T

tensor([[ True, False, False, False],
        [False,  True, False, False],
        [False, False,  True, False],
        [False, False, False,  True]])

In [25]:
X = torch.arange(24).reshape(2, 3, 4)
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [27]:
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
B = A[:]
A, A+B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

In [28]:
id(A) == id(B)

False

#### 哈达玛积

In [29]:
A * B

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

#### 和 均值

In [30]:
sum_A = A.sum()
mean_A = A.mean()
sum_A, mean_A

(tensor(190.), tensor(9.5000))

#### 在某个方向上求和

In [31]:
sum_A_dim = A.sum(axis=1, keepdims=True)
sum_A_dim

tensor([[ 6.],
        [22.],
        [38.],
        [54.],
        [70.]])

#### 向量的点积

In [34]:
X = torch.arange(4, dtype=torch.float32)
y = torch.ones(4, dtype=torch.float32)
X, y, torch.dot(X, y)

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.))

#### 矩阵乘向量

In [38]:
A = torch.arange(20, dtype=torch.float32).reshape(5,4)
A.shape, X.shape, torch.mv(A, X)

(torch.Size([5, 4]), torch.Size([4]), tensor([ 14.,  38.,  62.,  86., 110.]))

#### 矩阵乘矩阵

In [39]:
B = torch.ones(4, 3)
torch.mm(A, B)

tensor([[ 6.,  6.,  6.],
        [22., 22., 22.],
        [38., 38., 38.],
        [54., 54., 54.],
        [70., 70., 70.]])

#### L1范数

In [40]:
u = torch.arange(4)
torch.abs(u).sum()

tensor(6)

#### f范数 (每个元素的平方和再开根号)

In [41]:
torch.norm(torch.ones((4, 9)))

tensor(6.)

In [56]:
v = torch.arange(1,4, dtype=torch.float32).reshape(3, 1)
m = torch.ones(9).reshape(3, 3)
v.shape, m.shape, torch.mm(m, v)

(torch.Size([3, 1]),
 torch.Size([3, 3]),
 tensor([[6.],
         [6.],
         [6.]]))

In [52]:
v = torch.arange(1,4, dtype=torch.float32)
m = torch.ones(9).reshape(3, 3)
v.shape, m.shape, torch.mv(m, v)

(torch.Size([3]), torch.Size([3, 3]), tensor([6., 6., 6.]))