In [12]:
import torch
import torch.nn.functional as F
from torch import nn

class CenteredLayer(nn.Module):
    def __init__(self):
        super().__init__()
    
    def forward(self, X):
        return X - X.mean()

layer = CenteredLayer()
layer(torch.FloatTensor([1, 2, 3, 4, 5]))

tensor([-2., -1.,  0.,  1.,  2.])

In [13]:
net = nn.Sequential(nn.Linear(8, 8), CenteredLayer())

Y = net(torch.rand(4, 8))
Y.mean()

tensor(7.4506e-09, grad_fn=<MeanBackward0>)

### 自定义一个层

In [18]:
class MyLinear(nn.Module):
    def __init__(self, in_units, units):
        super().__init__()
        self.weight = nn.Parameter(torch.randn(in_units, units))
        self.bias = nn.Parameter(torch.randn(units,))

    def forward(self, X):
        linear = torch.matmul(X, self.weight.data) + self.bias.data
        return F.relu(linear)

dense = MyLinear(5, 3)
dense.weight

Parameter containing:
tensor([[-1.0884, -2.0092, -0.4926],
        [ 1.7283, -0.9850, -0.2942],
        [ 0.7355, -0.1865,  1.4665],
        [ 0.5266,  0.5682,  2.1019],
        [ 0.6352, -2.1530, -0.0425]], requires_grad=True)

In [19]:
dense(torch.rand(2, 5))

tensor([[1.4120, 0.0000, 1.9796],
        [2.2240, 0.0000, 3.5429]])

In [20]:
net = nn.Sequential(MyLinear(64, 8), MyLinear(8, 1))
net(torch.rand(2, 64))

tensor([[0.0000],
        [2.5129]])